spring.application.name=soloTest

spring.datasource.url = jdbc:postgresql://localhost:5432/dimas_ecommerce
spring.datasource.username = postgres
spring.datasource.password = root
spring.datasource.driver-class-name=org.postgresql.Driver

#IMAGE DIRECTORY
file.IMAGE_DIR = src/main/resources/static/images/

#JWT SECRET
jwt.secret=secret-1234567890

# Konfigurasi path gambar
spring.mvc.static-path-pattern=/images/**
spring.web.resources.static-locations=file:/Users/sulaksono/Bootcamp/soloTest/src/main/resources/static/images/

spring.web.resources.add-mappings=true
